#!/usr/bin/env bash
set -euo pipefail

BUILD_DIR="${BUILD_DIR:-/project/build}"

# make configuration available to the gerby package, then pin BUILD_DIR
cp /project/content/configuration.py /app/gerby-website/gerby/configuration.py
echo "BUILD_DIR = \"${BUILD_DIR}\"" >> /app/gerby-website/gerby/configuration.py

# ensure build directory exists
mkdir -p "${BUILD_DIR}"

# 1) update tags file with new tags
/app/venv-gerby/bin/python3 /app/tagger.py /project/content/tex/document.tex /project/content/tags >> /project/content/tags

# 2) convert to HTML: run plastex from BUILD_DIR so output lands in BUILD_DIR/document/
#    plastex's Gerby renderer looks for the tags file and any .bib files relative to its working directory
cp /project/content/tags "${BUILD_DIR}/tags"
cp /project/content/tex/*.bib "${BUILD_DIR}/" 2>/dev/null || true
# Use the .bbl generated by the plastex service (which runs latex+bibtex) if available.
# Without it natbib falls back to numeric labels.
cp /project/build/plastex/document.bbl "${BUILD_DIR}/" 2>/dev/null || true
cp /project/build/plastex/document.aux "${BUILD_DIR}/" 2>/dev/null || true
cd "${BUILD_DIR}"
rm -rf "${BUILD_DIR}/document"
/app/venv-plastex/bin/plastex --renderer=Gerby ${PLASTEX_PLUGINS:+--plugins=$PLASTEX_PLUGINS} /project/content/tex/document.tex

# 3) import plasTeX output into database
/app/venv-gerby/bin/python3 /app/gerby-website/gerby/tools/update.py
