x-gerby-build: &gerby-build
  context: .
  args:
    PLASTEX_REPO: https://github.com/koffie/plastex.git
    PLASTEX_HASH: 0719772bae931d356de012ca1518cc3fb8ef34f0
    GERBY_REPO: https://github.com/koffie/gerby-website.git
    GERBY_HASH: 052565e9194acdd5eacb16718aae2121f0186a1c
    BONSAI_REPO: https://github.com/aexmachina/jquery-bonsai
    BONSAI_HASH: a7f2e280e374ce649b5b543af0102a5ed107b854

x-gerby-volumes: &gerby-volumes
  - .:/project
  - /Users/mderickx/code/one_project_to_rule_them_all/libs/gerby-website:/app/gerby-website

services:
  gerby:
    build: *gerby-build
    volumes: *gerby-volumes
    ports:
      - "8080:5000"
    environment:
      FLASK_DEBUG: "1"
      PYTHONPATH: /app/gerby-website

  watcher:
    build: *gerby-build
    volumes: *gerby-volumes
    environment:
      PYTHONPATH: /app/gerby-website
    entrypoint: ["/app/entrypoint-watch.sh"]
    depends_on:
      - gerby
